### ISSUE TITLE
Manual stream offsets

### ISSUE THREAD

**Issue by bibixx** [bibixx/zium.app#16]

**Comment by toiletgranny** [comment]
The component can be found here: https://www.figma.com/file/JCMfY8OFGmiDT3lEzSX6zS/Zium.app-Designs?type=design&node-id=892-10740&mode=design&t=vam4AdzqgFFocQ77-4



![Image](https://github.com/bibixx/zium.app/assets/35307309/fab063f1-f3f4-45a9-8750-69c9cff92f68)


Please note that the nested `Button` and `Input` components have padding reduced by `4px` in order to fit within a container that's of an equal height as the regular `Button` component.

The idea here is for the user to be able to specify the offset manually by typing it into the input field, or by pressing one of the buttons. The increment/decrement for plus & minus buttons is to be determined later, through testing & experimentation and finding what feels right. For now, I'd suggest going with `.25s`.
